// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelService.Models;

public partial class BOOKING
{
    public int user_id { get; set; }

    public int tour_id { get; set; }

    public DateTime? time { get; set; }

    public virtual TOUR tour { get; set; }

    public virtual USER user { get; set; }
}