// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelService.Models;

public partial class Category
{
    public int id { get; set; }

    public string name { get; set; }

    public virtual ICollection<Tour> Tours { get; set; } = new List<Tour>();
}