// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelService.Models;

public partial class Customer_Order
{
    public int id { get; set; }

    public DateOnly? date { get; set; }

    public string payment_code { get; set; }

    public string status { get; set; }

    public long? total { get; set; }

    public int customer_id { get; set; }

    public int employee_id { get; set; }

    public virtual Customer customer { get; set; }

    public virtual Employee employee { get; set; }
}