// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelService.Models;

public partial class Customer
{
    public int id { get; set; }

    public string name { get; set; }

    public DateOnly? dob { get; set; }

    public string address { get; set; }

    public string phone { get; set; }

    public string email { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public virtual ICollection<Customer_Order> Customer_Orders { get; set; } = new List<Customer_Order>();
}