// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelService.Models;

public partial class FLIGHT
{
    public int id { get; set; }

    public string code { get; set; }

    public string airline { get; set; }

    public string flight_from { get; set; }

    public string flight_to { get; set; }

    public DateTime? departure { get; set; }

    public DateTime? arrival { get; set; }

    public int place_id { get; set; }

    public virtual ICollection<TOUR> TOURs { get; set; } = new List<TOUR>();
}