// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelService.Models;

public partial class ROLE
{
    public int id { get; set; }

    public string name { get; set; }

    public virtual ICollection<USER> USERs { get; set; } = new List<USER>();
}