// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelService.Models;

public partial class Role
{
    public int id { get; set; }

    public string name { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}