// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelService.Models;

public partial class Tour
{
    public int id { get; set; }

    public string name { get; set; }

    public long? price { get; set; }

    public string duration { get; set; }

    public string picture { get; set; }

    public int category_id { get; set; }

    public virtual ICollection<Tour_Detail> Tour_Details { get; set; } = new List<Tour_Detail>();

    public virtual Category category { get; set; }
}