// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelService.Models;

public partial class Tour_Detail
{
    public int id { get; set; }

    public string code { get; set; }

    public DateOnly? begin_date { get; set; }

    public DateOnly? end_date { get; set; }

    public string transport { get; set; }

    public string start_destination { get; set; }

    public int tour_id { get; set; }

    public virtual ICollection<Tour_Details_Image> Tour_Details_Images { get; set; } = new List<Tour_Details_Image>();

    public virtual Tour tour { get; set; }
}