// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelService.Models;

public partial class TOUR
{
    public int id { get; set; }

    public string code { get; set; }

    public string description { get; set; }

    public string details { get; set; }

    public string start_destination { get; set; }

    public string finish_destination { get; set; }

    public DateOnly? begin_date { get; set; }

    public DateOnly? end_date { get; set; }

    public double? price { get; set; }

    public int place_id { get; set; }

    public int hotel_id { get; set; }

    public int car_id { get; set; }

    public int flight_id { get; set; }

    public virtual ICollection<BOOKING> BOOKINGs { get; set; } = new List<BOOKING>();

    public virtual CAR car { get; set; }

    public virtual FLIGHT flight { get; set; }

    public virtual HOTEL hotel { get; set; }

    public virtual PLACE place { get; set; }
}