// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelService.Models;

public partial class USER
{
    public int id { get; set; }

    public string name { get; set; }

    public string address { get; set; }

    public string phone { get; set; }

    public string email { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public int role_id { get; set; }

    public virtual ICollection<BOOKING> BOOKINGs { get; set; } = new List<BOOKING>();

    public virtual ROLE role { get; set; }
}